// <auto-generated />
namespace QuanLyDoAnLastest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_tbl_accounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tbl_accounts));
        
        string IMigrationMetadata.Id
        {
            get { return "202011261454127_update_tbl_accounts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
