// <auto-generated />
namespace QuanLyDoAnLastest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Trying_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Trying_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202011301349165_Trying_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
